export default [
  {
    id: 1,
    header: 'Bookstore',
    authorLang: ' PERSONAL',
    authorList1: 'Front End Dev',
    authorList2: '2022',
    imgSrc: 'assets/images/background_image/bookstore.png',
    para: 'Bookstore is an app that allows you to display a list of added books, add new book and remove a book.',
    langList1: 'react',
    langList2: 'redux',
    langList3: 'styled-components',
    langList4: 'javascript',
    link1: 'https://ans-bookstore.netlify.app/',
    link2: 'https://github.com/AnselemOdims/Bookstore',
  },
  {
    id: 2,
    header: 'CryptoFest',
    authorLang: 'PERSONAL',
    authorList1: 'Front End Dev',
    authorList2: '2021',
    imgSrc: 'assets/images/screenshot/cryotfest.png',
    para: `CryptoFest is a website that announces annual worldwide Crypto
    conference to discuss crypto-related issues`,
    langList1: 'html',
    langList2: 'scss',
    langList3: 'javascript',
    link1: 'https://anselemodims.github.io/CryptoFest/',
    link2: 'https://github.com/AnselemOdims/Portfolio',
  },
  {
    id: 3,
    header: 'MazeFlix',
    authorLang: 'PERSONAL',
    authorList1: 'Front End Dev',
    authorList2: '2021',
    imgSrc: 'assets/images/background_image/mazeflix-1.png',
    para: ` MazeFlix is an entertainment hub where you can find the latest and
    your favorite TV shows. You can view the details of the show, like
    a show or even comment. You can also see other comments which
    might give you a general idea about what people think about the
    show.`,
    langList1: 'html',
    langList2: 'css',
    langList3: 'javascript',
    langList4: 'webpack',
    link1: 'https://anselemodims.github.io/MazeFlix/',
    link2: 'https://github.com/AnselemOdims/MazeFlix',
  },
  {
    id: 4,
    header: 'LeaderBoard',
    authorLang: 'PERSONAL',
    authorList1: 'Front End Dev',
    authorList2: '2021',
    imgSrc: 'assets/images/background_image/leaderboard.png',
    para: ` The leaderboard website displays scores submitted by different players. It also allows you to submit your score. 
    All data is preserved thanks to the external Leaderboard API service.`,
    langList1: 'html',
    langList2: 'css',
    langList3: 'javascript',
    langList4: 'webpack',
    link1: 'https://anselemodims.github.io/LeaderBoard/',
    link2: 'https://github.com/AnselemOdims/LeaderBoard',
  },
  {
    id: 5,
    header: 'To-Do',
    authorLang: 'PERSONAL',
    authorList1: 'Front End Dev',
    authorList2: '2021',
    imgSrc: 'assets/images/background_image/todo-1.png',
    para: `To-do is a web app that helps to organize your day-to-day
    activities. It lists all the activities that you need to be
    completed and allows you to mark them as complete or not.`,
    langList1: 'html',
    langList2: 'css',
    langList3: 'javascript',
    langList4: 'webpack',
    link1: 'https://anselemodims.github.io/To-Do/',
    link2: 'https://github.com/AnselemOdims/To-Do',
  },
];
