export default [
  {
    id: 1,
    header: 'Tonic',
    authorLang: 'CANOPY',
    authorList1: 'Back End Dev',
    authorList2: '2015',
    imgSrc: 'assets/images/background_image/first_large.png',
    para: `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quibusdam,
    explicabo. Dolorum eum vitae, quae voluptatem earum debitis minus, facere,
    at tenetur excepturi nihil! Commodi tenetur cumque iure quos nesciunt sunt!`,
    langList1: 'html',
    langList2: 'css',
    langList3: 'javascript',
  },
  {
    id: 2,
    header: 'Multi Post Stories',
    authorLang: 'FACEBOOK',
    authorList1: 'Full Stack Dev',
    authorList2: '2015',
    imgSrc: 'assets/images/background_image/second_large.png',
    para: `    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quibusdam,
    explicabo. Dolorum eum vitae, quae voluptatem earum debitis minus, facere,
    at tenetur excepturi nihil! Commodi tenetur cumque iure quos nesciunt sunt!`,
    langList1: 'html',
    langList2: 'ruby on rails',
    langList3: 'css',
    langList4: 'javascript',
  },
  {
    id: 3,
    header: 'Facebook 360',
    authorLang: 'FACEBOOK',
    authorList1: 'Full Stack Dev',
    authorList2: '2015',
    imgSrc: 'assets/images/background_image/third_large.png',
    para: ` Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quibusdam,
    explicabo. Dolorum eum vitae, quae voluptatem earum debitis minus, facere,
    at tenetur excepturi nihil! Commodi tenetur cumque iure quos nesciunt sunt!`,
    langList1: 'html',
    langList2: 'ruby on rails',
    langList3: 'css',
    langList4: 'javascript',
  },
  {
    id: 4,
    header: 'Uber Navigation',
    authorLang: 'Uber',
    authorList1: 'Lead Developer',
    authorList2: '2018',
    imgSrc: 'assets/images/background_image/fourth_large.png',
    para: ` Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quibusdam,
    explicabo. Dolorum eum vitae, quae voluptatem earum debitis minus, facere,
    at tenetur excepturi nihil! Commodi tenetur cumque iure quos nesciunt sunt!`,
    langList1: 'html',
    langList2: 'ruby on rails',
    langList3: 'css',
    langList4: 'javascript',
  },
];
